spring:
  profiles:
    active: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB
  datasource:
    url: jdbc:mysql://54.183.188.96:3306/digital_timbersaw?useSSL=false&useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    database: mysql
  jackson:
    default-property-inclusion: non_absent
    time-zone: UTC
    date-format: yyyy-MM-dd HH:mm:ss

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

server:
  servlet:
    context-path: /api
  port: 80

upload:
  file:
    base-path: /data/test/
